export { BackendHttpAdapter } from './BackendHttpAdapter'
export { ChromeStorageCredentialAdapter } from './ChromeStorageCredentialAdapter'
export { CMSInjectionAdapter } from './CMSInjectionAdapter'
export { DOMExtractorAdapter } from './DOMExtractorAdapter'
export { LabelAdapter } from './LabelAdapter'
export { PageAdapter } from './PageAdapter'
export { WSClientAdapter } from './WSClientAdapter'
